site_title = "ArxivDaily"
limit_days = 7
cache_url = "https://arxiv.alongwy.top/cache.json"


[[sources]]
limit = 500
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 200
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 100
category = "cs.MM"
title = "Multimedia"

[[sources]]
limit = 100
category = "cs.HC"
title = "Human-Computer Interaction"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
